import { BarberService, SubscriptionPlan, User, Booking, AbsenceDay, CashTransaction, BarberAvailabilityConfig, InfinitePayConfig } from './types';

export const INITIAL_INFINITEPAY_CONFIG: InfinitePayConfig = {
  merchantName: 'Barbearia Belchior',
  defaultUrl: 'https://pay.infinitepay.io/barbearia-belchior',
  enabled: true,
  notes: 'Pagamento via Cartão de Crédito ou Débito com a segurança e aprovação imediata da InfinitePay.',
};

export const INITIAL_SERVICES: BarberService[] = [
  {
    id: 'serv-1',
    name: 'Corte Cabelo Clássico / Fade',
    category: 'Cabelo',
    price: 45.0,
    durationMinutes: 40,
    description: 'Corte moderno com tesoura e máquina, degradê navalhado, acabamento preciso e finalização com pomada modeladora.',
    isActive: true,
  },
  {
    id: 'serv-2',
    name: 'Barba Terapia Completa',
    category: 'Barba',
    price: 35.0,
    durationMinutes: 30,
    description: 'Toalha quente com óleos essenciais, massagem facial, lâmina descartável, esfoliação e balm hidratante.',
    isActive: true,
  },
  {
    id: 'serv-3',
    name: 'Combo Barba & Cabelo Executivo',
    category: 'Combo',
    price: 70.0,
    durationMinutes: 60,
    description: 'O combo mais pedido: Corte de cabelo completo + Barboterapia com toalha quente e bebida cortesia.',
    isActive: true,
  },
  {
    id: 'serv-4',
    name: 'Pigmentação de Barba & Cabelo',
    category: 'Tratamento',
    price: 40.0,
    durationMinutes: 30,
    description: 'Disfarce óptico de fios brancos e falhas com tonalizante profissional de longa durabilidade.',
    isActive: true,
  },
  {
    id: 'serv-5',
    name: 'Alinhamento Capilar / Botox',
    category: 'Tratamento',
    price: 80.0,
    durationMinutes: 50,
    description: 'Tratamento redutor de volume e frizz com nutrição profunda para fios macios e fáceis de pentear.',
    isActive: true,
  },
  {
    id: 'serv-6',
    name: 'Sobrancelha na Navalha / Pinça',
    category: 'Outros',
    price: 15.0,
    durationMinutes: 15,
    description: 'Design de sobrancelha masculina natural e alinhamento do contorno.',
    isActive: true,
  },
];

export const INITIAL_SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  {
    id: 'plan-basic',
    name: 'Clube Essencial',
    monthlyPrice: 89.90,
    description: 'Ideal para quem gosta de manter o cabelo sempre na régua.',
    includedServicesDescription: '2 Cortes de Cabelo por mês + 10% de desconto em outros serviços',
    maxBookingsPerMonth: 2,
    discountPercentageOnOthers: 10,
    infinitePayUrl: 'https://pay.infinitepay.io/barbearia-belchior/clube-essencial',
    isActive: true,
  },
  {
    id: 'plan-vip',
    name: 'Clube Vip Master (Ilimitado)',
    monthlyPrice: 149.90,
    description: 'O plano mais procurado por clientes frequentes e executivos.',
    includedServicesDescription: 'Cortes & Barbas ILIMITADOS no mês + 1 Bebida especial por visita + 20% off em produtos',
    maxBookingsPerMonth: -1, // Unlimited
    discountPercentageOnOthers: 20,
    popular: true,
    infinitePayUrl: 'https://pay.infinitepay.io/barbearia-belchior/clube-vip',
    isActive: true,
  },
  {
    id: 'plan-barba',
    name: 'Clube Barba Alinhada',
    monthlyPrice: 79.90,
    description: 'Para os barbudos de respeito que exigem cuidados semanais.',
    includedServicesDescription: '4 Barboterapias completas com toalha quente no mês + 15% off em pomadas/óleos',
    maxBookingsPerMonth: 4,
    discountPercentageOnOthers: 15,
    infinitePayUrl: 'https://pay.infinitepay.io/barbearia-belchior/clube-barba',
    isActive: true,
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'user-admin',
    name: 'Belchior (Administrador)',
    email: 'belchior87@gmail.com',
    phone: '(11) 98765-4321',
    role: 'ADMIN',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'user-client-1',
    name: 'Lucas Silveira',
    email: 'lucas.silveira@email.com',
    phone: '(11) 99123-4567',
    role: 'CLIENT',
    subscriptionId: 'plan-vip',
    subscriptionStartDate: '2026-08-01',
    createdAt: '2026-06-15T14:30:00Z',
  },
  {
    id: 'user-client-2',
    name: 'Rafael Mendes',
    email: 'rafael.mendes@email.com',
    phone: '(11) 99876-1122',
    role: 'CLIENT',
    createdAt: '2026-07-20T11:00:00Z',
  },
  {
    id: 'user-client-3',
    name: 'Carlos Eduardo Fontes',
    email: 'cadu.fontes@email.com',
    phone: '(11) 97711-3344',
    role: 'CLIENT',
    createdAt: '2026-05-10T09:00:00Z',
  },
  {
    id: 'user-client-4',
    name: 'Matheus Albuquerque',
    email: 'matheus.a@email.com',
    phone: '(11) 98822-6677',
    role: 'CLIENT',
    subscriptionId: 'plan-basic',
    subscriptionStartDate: '2026-08-15',
    createdAt: '2026-08-05T16:20:00Z',
  }
];

export const INITIAL_AVAILABILITY_CONFIG: BarberAvailabilityConfig = {
  openTime: '09:00',
  closeTime: '20:00',
  intervalMinutes: 30,
  lunchStart: '12:00',
  lunchEnd: '13:00',
  workingDays: [1, 2, 3, 4, 5, 6], // Segunda a Sábado
};

export const INITIAL_ABSENCE_DAYS: AbsenceDay[] = [
  {
    id: 'abs-1',
    date: '2026-09-07',
    reason: 'Feriado Nacional - Independência do Brasil',
  },
  {
    id: 'abs-2',
    date: '2026-09-21',
    reason: 'Workshop & Aperfeiçoamento Master Barber',
  }
];

// Helper to get formatted current local date
const today = '2026-09-02';

export const INITIAL_BOOKINGS: Booking[] = [
  // Today's bookings
  {
    id: 'book-101',
    clientId: 'user-client-1',
    clientName: 'Lucas Silveira',
    clientPhone: '5511991234567',
    clientEmail: 'lucas.silveira@email.com',
    serviceId: 'serv-3',
    serviceName: 'Combo Barba & Cabelo Executivo',
    servicePrice: 70.0,
    durationMinutes: 60,
    barberName: 'Belchior Barber',
    date: '2026-09-02',
    time: '14:00',
    status: 'AGENDADO',
    paymentMethod: 'ASSINATURA_CLUBE',
    isPaid: true,
    recurrenceType: 'WEEKLY',
    notes: 'Cliente do Plano VIP',
    createdAt: '2026-09-01T10:00:00Z',
    reminderSent: false,
  },
  {
    id: 'book-102',
    clientId: 'user-client-2',
    clientName: 'Rafael Mendes',
    clientPhone: '5511998761122',
    clientEmail: 'rafael.mendes@email.com',
    serviceId: 'serv-1',
    serviceName: 'Corte Cabelo Clássico / Fade',
    servicePrice: 45.0,
    durationMinutes: 40,
    barberName: 'Belchior Barber',
    date: '2026-09-02',
    time: '16:00',
    status: 'AGENDADO',
    paymentMethod: 'PENDENTE',
    isPaid: false,
    notes: 'Degradê na zero navalhada',
    createdAt: '2026-09-01T15:20:00Z',
    reminderSent: false,
  },
  {
    id: 'book-103',
    clientId: 'user-client-4',
    clientName: 'Matheus Albuquerque',
    clientPhone: '5511988226677',
    clientEmail: 'matheus.a@email.com',
    serviceId: 'serv-2',
    serviceName: 'Barba Terapia Completa',
    servicePrice: 35.0,
    durationMinutes: 30,
    barberName: 'Belchior Barber',
    date: '2026-09-02',
    time: '10:00',
    status: 'EXECUTADO',
    paymentMethod: 'PIX',
    isPaid: true,
    createdAt: '2026-08-30T11:00:00Z',
    reminderSent: true,
  },
  // Upcoming bookings this week
  {
    id: 'book-104',
    clientId: 'user-client-3',
    clientName: 'Carlos Eduardo Fontes',
    clientPhone: '5511977113344',
    clientEmail: 'cadu.fontes@email.com',
    serviceId: 'serv-3',
    serviceName: 'Combo Barba & Cabelo Executivo',
    servicePrice: 70.0,
    durationMinutes: 60,
    barberName: 'Belchior Barber',
    date: '2026-09-03',
    time: '15:00',
    status: 'AGENDADO',
    paymentMethod: 'CARTAO_CREDITO',
    isPaid: false,
    createdAt: '2026-09-01T18:00:00Z',
    reminderSent: false,
  },
  {
    id: 'book-105',
    clientId: 'user-client-1',
    clientName: 'Lucas Silveira',
    clientPhone: '5511991234567',
    clientEmail: 'lucas.silveira@email.com',
    serviceId: 'serv-3',
    serviceName: 'Combo Barba & Cabelo Executivo',
    servicePrice: 70.0,
    durationMinutes: 60,
    barberName: 'Belchior Barber',
    date: '2026-09-09',
    time: '14:00',
    status: 'AGENDADO',
    paymentMethod: 'ASSINATURA_CLUBE',
    isPaid: true,
    recurrenceType: 'WEEKLY',
    createdAt: '2026-09-01T10:00:00Z',
  },
  {
    id: 'book-106',
    clientId: 'user-client-1',
    clientName: 'Lucas Silveira',
    clientPhone: '5511991234567',
    clientEmail: 'lucas.silveira@email.com',
    serviceId: 'serv-3',
    serviceName: 'Combo Barba & Cabelo Executivo',
    servicePrice: 70.0,
    durationMinutes: 60,
    barberName: 'Belchior Barber',
    date: '2026-09-16',
    time: '14:00',
    status: 'AGENDADO',
    paymentMethod: 'ASSINATURA_CLUBE',
    isPaid: true,
    recurrenceType: 'WEEKLY',
    createdAt: '2026-09-01T10:00:00Z',
  },
  // Past executed and cancelled bookings for reporting & metrics
  {
    id: 'book-090',
    clientId: 'user-client-2',
    clientName: 'Rafael Mendes',
    clientPhone: '5511998761122',
    clientEmail: 'rafael.mendes@email.com',
    serviceId: 'serv-1',
    serviceName: 'Corte Cabelo Clássico / Fade',
    servicePrice: 45.0,
    durationMinutes: 40,
    barberName: 'Belchior Barber',
    date: '2026-08-25',
    time: '17:00',
    status: 'EXECUTADO',
    paymentMethod: 'PIX',
    isPaid: true,
    createdAt: '2026-08-22T09:00:00Z',
  },
  {
    id: 'book-091',
    clientId: 'user-client-3',
    clientName: 'Carlos Eduardo Fontes',
    clientPhone: '5511977113344',
    clientEmail: 'cadu.fontes@email.com',
    serviceId: 'serv-2',
    serviceName: 'Barba Terapia Completa',
    servicePrice: 35.0,
    durationMinutes: 30,
    barberName: 'Belchior Barber',
    date: '2026-08-28',
    time: '18:00',
    status: 'CANCELADO',
    cancelReason: 'Imprevisto no trabalho de última hora',
    cancelledAt: '2026-08-28T14:30:00Z',
    paymentMethod: 'PENDENTE',
    isPaid: false,
    createdAt: '2026-08-24T12:00:00Z',
  },
  {
    id: 'book-092',
    clientId: 'user-client-4',
    clientName: 'Matheus Albuquerque',
    clientPhone: '5511988226677',
    clientEmail: 'matheus.a@email.com',
    serviceId: 'serv-1',
    serviceName: 'Corte Cabelo Clássico / Fade',
    servicePrice: 45.0,
    durationMinutes: 40,
    barberName: 'Belchior Barber',
    date: '2026-08-15',
    time: '11:00',
    status: 'EXECUTADO',
    paymentMethod: 'DINHEIRO',
    isPaid: true,
    createdAt: '2026-08-12T10:00:00Z',
  },
  {
    id: 'book-093',
    clientId: 'user-client-2',
    clientName: 'Rafael Mendes',
    clientPhone: '5511998761122',
    clientEmail: 'rafael.mendes@email.com',
    serviceId: 'serv-5',
    serviceName: 'Alinhamento Capilar / Botox',
    servicePrice: 80.0,
    durationMinutes: 50,
    barberName: 'Belchior Barber',
    date: '2026-08-10',
    time: '14:00',
    status: 'CANCELADO',
    cancelReason: 'Sintomas gripais / saúde',
    cancelledAt: '2026-08-10T09:15:00Z',
    paymentMethod: 'PENDENTE',
    isPaid: false,
    createdAt: '2026-08-05T11:00:00Z',
  },
  {
    id: 'book-094',
    clientId: 'user-client-1',
    clientName: 'Lucas Silveira',
    clientPhone: '5511991234567',
    clientEmail: 'lucas.silveira@email.com',
    serviceId: 'serv-3',
    serviceName: 'Combo Barba & Cabelo Executivo',
    servicePrice: 70.0,
    durationMinutes: 60,
    barberName: 'Belchior Barber',
    date: '2026-08-26',
    time: '14:00',
    status: 'EXECUTADO',
    paymentMethod: 'ASSINATURA_CLUBE',
    isPaid: true,
    createdAt: '2026-08-20T10:00:00Z',
  }
];

export const INITIAL_TRANSACTIONS: CashTransaction[] = [
  {
    id: 'trans-1',
    type: 'ENTRADA',
    description: 'Atendimento: Barba Terapia - Matheus Albuquerque',
    amount: 35.0,
    paymentMethod: 'PIX',
    category: 'SERVICO',
    date: '2026-09-02T10:45:00Z',
    createdByName: 'Belchior Barber',
  },
  {
    id: 'trans-2',
    type: 'ENTRADA',
    description: 'Mensalidade Assinatura: Clube Vip Master - Lucas Silveira',
    amount: 149.90,
    paymentMethod: 'CARTAO_CREDITO',
    category: 'ASSINATURA',
    date: '2026-09-01T08:00:00Z',
    createdByName: 'Sistema Assinaturas',
  },
  {
    id: 'trans-3',
    type: 'SAIDA',
    description: 'Reposição de Lâminas e Toalhas Descartáveis',
    amount: 95.0,
    paymentMethod: 'PIX',
    category: 'PRODUTOS_SUPRIMENTOS',
    date: '2026-09-01T11:30:00Z',
    createdByName: 'Belchior Barber',
  },
  {
    id: 'trans-4',
    type: 'ENTRADA',
    description: 'Atendimento: Corte Cabelo Clássico - Rafael Mendes',
    amount: 45.0,
    paymentMethod: 'PIX',
    category: 'SERVICO',
    date: '2026-08-25T17:45:00Z',
    createdByName: 'Belchior Barber',
  },
  {
    id: 'trans-5',
    type: 'ENTRADA',
    description: 'Venda de Pomada Matte Modeladora Efeito Seco',
    amount: 50.0,
    paymentMethod: 'DINHEIRO',
    category: 'PRODUTO',
    date: '2026-08-25T17:50:00Z',
    createdByName: 'Belchior Barber',
  },
  {
    id: 'trans-6',
    type: 'SAIDA',
    description: 'Energia Elétrica / Ar Condicionado Barbearia',
    amount: 280.0,
    paymentMethod: 'PIX',
    category: 'DESPESA_FIXA',
    date: '2026-08-20T14:00:00Z',
    createdByName: 'Belchior Barber',
  }
];
